version: '3'

services:
  db:
    container_name: service_db
    image: postgres:latest
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    networks:
      - service

  drf:
    container_name: api
    build:
      context: .
    command: >
             sh -c "
             python src/manage.py makemigrations &&
             python src/manage.py migrate &&
             python src/manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - service
    restart: always
    depends_on:
      - db


networks:
  service:
    driver: bridge